"""add compound_name and molecule_metadata to search_history

Revision ID: 4d824f254932
Revises: d5828840b723
Create Date: 2026-07-15 09:54:11.057146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d824f254932'
down_revision: Union[str, Sequence[str], None] = 'd5828840b723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_history', sa.Column('compound_name', sa.String(), nullable=True))
    op.add_column('search_history', sa.Column('molecule_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_history', 'molecule_metadata')
    op.drop_column('search_history', 'compound_name')
    # ### end Alembic commands ###
