"""Initial

Revision ID: d5828840b723
Revises: 
Create Date: 2026-07-14 14:54:21.368691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5828840b723'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patent_number', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('publication_date', sa.String(), nullable=False),
    sa.Column('assignee', sa.String(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patents_patent_number'), 'patents', ['patent_number'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('google_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_patents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('patent_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patent_id'], ['patents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('input_smiles', sa.String(), nullable=False),
    sa.Column('input_target', sa.String(), nullable=True),
    sa.Column('input_disease', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_stage', sa.String(), nullable=True),
    sa.Column('progress_percentage', sa.Float(), nullable=False),
    sa.Column('execution_timeline', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_usage_tracking',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('input_tokens', sa.Float(), nullable=False),
    sa.Column('output_tokens', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('search_history_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['search_history_id'], ['search_history.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patent_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patent_id', sa.UUID(), nullable=False),
    sa.Column('search_history_id', sa.UUID(), nullable=False),
    sa.Column('why_retrieved', sa.Text(), nullable=False),
    sa.Column('key_similarities', sa.Text(), nullable=False),
    sa.Column('novelty_concerns', sa.Text(), nullable=False),
    sa.Column('potential_claim_overlap', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patent_id'], ['patents.id'], ),
    sa.ForeignKeyConstraint(['search_history_id'], ['search_history.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patent_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('search_history_id', sa.UUID(), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=False),
    sa.Column('top_similar_patents', sa.JSON(), nullable=False),
    sa.Column('novelty_concerns', sa.Text(), nullable=False),
    sa.Column('patents_requiring_manual_review', sa.JSON(), nullable=False),
    sa.Column('overall_recommendation', sa.String(), nullable=False),
    sa.Column('patent_risk_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['search_history_id'], ['search_history.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('search_history_id')
    )
    op.create_table('search_history_patents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('search_history_id', sa.UUID(), nullable=False),
    sa.Column('patent_id', sa.UUID(), nullable=False),
    sa.Column('component_scores', sa.JSON(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patent_id'], ['patents.id'], ),
    sa.ForeignKeyConstraint(['search_history_id'], ['search_history.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_history_patents_patent_id'), 'search_history_patents', ['patent_id'], unique=False)
    op.create_index(op.f('ix_search_history_patents_search_history_id'), 'search_history_patents', ['search_history_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_history_patents_search_history_id'), table_name='search_history_patents')
    op.drop_index(op.f('ix_search_history_patents_patent_id'), table_name='search_history_patents')
    op.drop_table('search_history_patents')
    op.drop_table('patent_reports')
    op.drop_table('patent_analyses')
    op.drop_table('llm_usage_tracking')
    op.drop_table('search_history')
    op.drop_table('saved_patents')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_patents_patent_number'), table_name='patents')
    op.drop_table('patents')
    # ### end Alembic commands ###
